//! Application-owned category tree.
//!
//! AI returns only a category/subcategory pair. The application maps that pair
//! to a relative folder. Arbitrary absolute paths generated by a model are
//! rejected.

use once_cell::sync::Lazy;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;

use crate::core::error::{AppError, AppResult};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Category {
    pub name: String,
    pub subcategories: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Fallback {
    pub category: String,
    pub subcategory: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CategoryTree {
    pub version: u32,
    pub categories: Vec<Category>,
    pub fallback: Fallback,
}

static TREE: Lazy<CategoryTree> = Lazy::new(|| CategoryTree {
    version: 1,
    categories: vec![
        cat("Documents", &["Research", "Notes", "Reports", "Legal", "Presentations"]),
        cat("Development", &["Code", "Documentation", "Screenshots", "Configs", "Databases"]),
        cat("Finance", &["Statements", "Invoices", "Receipts", "Taxes", "Budgets"]),
        cat("Images", &["Screenshots", "Photos", "Graphics", "Scans"]),
        cat("Books", &["Ebooks", "Papers", "Manuals"]),
        cat("Work", &["Projects", "Meetings", "Contracts"]),
        cat("Personal", &["Identity", "Health", "Travel", "Education"]),
        cat("Software", &["Installers", "Portable", "Licenses"]),
        cat("Archives", &["Zip", "Compressed", "Backups"]),
        cat("Other", &["Misc", "Unknown"]),
    ],
    fallback: Fallback {
        category: "Other".into(),
        subcategory: "Unknown".into(),
    },
});

fn cat(name: &str, subs: &[&str]) -> Category {
    Category {
        name: name.into(),
        subcategories: subs.iter().map(|s| (*s).to_string()).collect(),
    }
}

static LOOKUP: Lazy<HashMap<String, Vec<String>>> = Lazy::new(|| {
    TREE.categories
        .iter()
        .map(|c| (c.name.clone(), c.subcategories.clone()))
        .collect()
});

pub fn tree() -> &'static CategoryTree {
    &TREE
}

pub fn is_valid_category(category: &str) -> bool {
    LOOKUP.contains_key(category)
}

pub fn is_valid_subcategory(category: &str, subcategory: &str) -> bool {
    LOOKUP
        .get(category)
        .map(|subs| subs.iter().any(|s| s == subcategory))
        .unwrap_or(false)
}

pub fn normalize(category: &str, subcategory: Option<&str>) -> (String, String) {
    let cat = if is_valid_category(category) {
        category.to_string()
    } else {
        TREE.fallback.category.clone()
    };
    let subs = LOOKUP.get(&cat).cloned().unwrap_or_default();
    let sub = subcategory
        .filter(|s| subs.iter().any(|known| known == s))
        .map(|s| s.to_string())
        .or_else(|| {
            if subs.iter().any(|s| s == &TREE.fallback.subcategory) {
                Some(TREE.fallback.subcategory.clone())
            } else {
                subs.first().cloned()
            }
        })
        .unwrap_or_else(|| TREE.fallback.subcategory.clone());
    (cat, sub)
}

/// Maps a validated pair to an application-owned relative folder.
pub fn suggested_folder(category: &str, subcategory: Option<&str>) -> String {
    let (cat, sub) = normalize(category, subcategory);
    format!("{cat}/{sub}")
}

/// Rejects any path that looks absolute or tries to escape the category tree.
pub fn validate_target_folder(folder: &str) -> AppResult<(String, String)> {
    let cleaned = folder.replace('\\', "/");
    if cleaned.starts_with('/') || cleaned.contains(':') || cleaned.contains("..") {
        return Err(AppError::InvalidCategory(format!(
            "AI/user produced a disallowed folder path: {folder}"
        )));
    }
    let mut parts = cleaned.split('/');
    let category = parts.next().unwrap_or("Other");
    let subcategory = parts.next();
    if parts.next().is_some() {
        return Err(AppError::InvalidCategory(
            "folder may only be category/subcategory".into(),
        ));
    }
    if !is_valid_category(category) {
        return Err(AppError::InvalidCategory(category.into()));
    }
    let (cat, sub) = normalize(category, subcategory);
    Ok((cat, sub))
}
